feat: project deletion reminder.
NFDI4Chem/nmrxiv pull request #624
Opened 2022-11-22 16:53 UTC by NishaSharma14

2022-11-22 16:54 UTC, NishaSharma14 commented
![image](https://user-images.githubusercontent.com/54287612/203374450-ea978e20-6b5c-4e2b-93b5-0c27639c76ce.png)

2022-11-30 15:46 UTC, CS76 requested changes

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +            }
extend the model to have a function that returns users with the specified roles

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +        }
- Rename command
- Enable options to provide project ids to be deleted and if null all the projects are checked

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +        }
use logs instead echo

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +        }
deleteFSO in Draft controller needs to be referred

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +                }
use pluck

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +                $nmriumInfo->delete();
$nmriumVersions = $nmrium->getLatestVersions()->get();

$nmriumVersions ->each(function ($version) {
    $version->delete();
});

2022-11-30 15:46 UTC, vcnainala commented on app/Console/Commands/DeleteTrashedProject.php
> +            }
DB transaction

2022-12-02 12:04 UTC, CS76 requested changes

2022-12-02 12:04 UTC, vcnainala commented on app/Mail/ProjectDeletionReminder.php
> +        ])->subject(__('Your project would be deleted soon'.' - '.$this->project->name));
replace would with will

2022-12-02 12:04 UTC, vcnainala commented on app/Actions/Project/DeleteProject.php
> +            $this->sendNotification($project);
Remove

2022-12-02 12:04 UTC, vcnainala commented on app/Actions/Project/DeleteProject.php
> +        Notification::send($sendTo, new ProjectDeletionNotification($project));
Add template for project archived notification / mailable

2022-12-02 12:04 UTC, vcnainala commented on resources/views/vendor/mail/project-deletion.blade.php
> +
Dear nmrXiv user,

Your nmrXiv project <project name> was deleted on <date time(TZ)>.
You may recover deleted projects and the data stored in them for a limited time before they are permanently deleted. If you’d like to recover your project, you must cancel the project’s permanent deletion before <date time(TZ)>.

To recover your deleted project:
Visit the thrash page (click the button below).
Select the project you want to recover, and click Project settings >  Restore.
In the confirmation dialogue, click Restore.

If you take no action by <date time(TZ)>, you will be unable to recover your project.

For further questions, please visit our documentation site or contact us at info@nmrxiv.org.

Regards,
The nmrXiv Team

2022-12-02 12:04 UTC, vcnainala commented on resources/views/vendor/mail/project-deletion-reminder.blade.php
> +
Dear nmrXiv user,

Your nmrXiv project <project name> was scheduled to be permanently deleted on <date time(TZ)>.
You may recover deleted projects and the data stored in them for a limited time before they are permanently deleted. If you’d like to recover your project, you must cancel the project’s permanent deletion before <date time(TZ)>.

To recover your deleted project:
Visit the thrash page (link).
Select the project you want to recover, and click Project settings >  Restore.
In the confirmation dialogue, click Restore.

If you take no action by <date time(TZ)>, you will be unable to recover your project.

For further questions, please visit our documentation site or contact us at info@nmrxiv.org.

Regards,
The nmrXiv Team

2022-12-02 12:04 UTC, vcnainala commented on resources/views/vendor/mail/project-archival-notify-admins.php
> +
Please add project name and identifier. Action button should take us there.

2022-12-02 12:04 UTC, CS76 commented on resources/views/vendor/mail/project-archival.php
> +Dear nmrXiv user,
Dear nmrXiv user,

Your nmrXiv project <project name> was flagged as archived on <date time(TZ)>.

A warning will now be displayed on your project, indicating that the project is no longer maintained.

You may unarchive your project if you would like to. To unarchive your project:
Visit the project page (link).
Select the project you want to unarchive, and click Project settings >  Unarchive.
In the confirmation dialogue, click confirm.

For further questions, please visit our documentation site or contact us at info@nmrxiv.org.

Regards,
The nmrXiv Team

2022-12-02 12:04 UTC, CS76 commented on resources/views/vendor/mail/project-deletion-failure.php
> +
Project name - identifier and any other error-related details.

2022-12-02 12:41 UTC, NishaSharma14 commented on resources/views/vendor/mail/project-deletion.blade.php
> +
![image](https://user-images.githubusercontent.com/54287612/205295320-e2bd2928-ead9-4be9-9cb7-263c5b057d3d.png)

2022-12-02 13:00 UTC, NishaSharma14 commented on resources/views/vendor/mail/project-archival.php
> +Dear nmrXiv user,
"Your nmrXiv project was flagged as archived on" the tone should not be past-tense, cuz this mail will sent immediately once user archive the project.

Instead - Your nmrXiv project has been flagged as archived successfully on

2022-12-02 14:28 UTC, NishaSharma14 commented on app/Actions/Project/DeleteProject.php
> +                throw $e;
send notification first and then throw error

2022-12-02 14:34 UTC, NishaSharma14 commented on app/Actions/Project/DeleteProject.php
> +                throw $e;
move cool-off period value to config(app.php)

2022-12-02 14:38 UTC, NishaSharma14 commented on resources/views/vendor/mail/project-archival.blade.php
> +Visit the project page (link).
Add message on separate lines for all mails

2022-12-05 11:35 UTC, merged