fix: add sender's details in project invite mail
NFDI4Chem/nmrxiv pull request #658
Opened 2022-12-05 16:23 UTC by NishaSharma14

Fixes #656

2022-12-05 16:24 UTC, NishaSharma14 commented
![image](https://user-images.githubusercontent.com/54287612/205688597-f0565a74-8568-4489-a36a-f9cad124058f.png)

2022-12-29 09:19 UTC, CS76 requested changes

2022-12-29 09:19 UTC, CS76 commented on app/Actions/Project/InviteProjectMember.php
> +            'invited_by' => $user->id,
Pass the user name and concatenate the name directly to avoid additional DB query

2022-12-29 09:19 UTC, CS76 commented on resources/views/vendor/mail/study-invitation.blade.php
> +{{ __('You have been invited to join the study **:study** by :invitedBy as role :role', ['study' => $invitation->study->name, 'invitedBy' => $invitedBy,'role' => $invitation->role]) }}
{{ __('You have been invited to join (role: :role) the study **:study** by :invitedBy', ['study' => $invitation->study->name, 'invitedBy' => $invitedBy,'role' => $invitation->role]) }}

2022-12-29 10:53 UTC, NishaSharma14 commented
![image](https://user-images.githubusercontent.com/54287612/209941194-d57c84b7-ca2e-49c1-862e-0e547f81aa0b.png)

2023-01-11 12:39 UTC, CS76 approved these changes

2023-01-11 12:39 UTC, merged