Info mail
NFDI4Chem/nmrxiv pull request #750
Opened 2023-01-19 20:54 UTC by NRayya

2023-01-20 06:41 UTC, NishaSharma14 requested changes

2023-01-20 06:41 UTC, NishaSharma14 commented on resources/js/App/Onboarding.vue
> +                                                        >{{ mailFromAddress }}
{{ this.$page.props.mailFromAddress }}

2023-01-20 06:50 UTC, NishaSharma14 requested changes

2023-01-20 06:50 UTC, NishaSharma14 commented on resources/js/App/Onboarding.vue
> +                                                    <a href="mailTo()"
add : before href `:href="mailTo()"`

2023-01-27 10:45 UTC, CS76 approved these changes

2023-01-27 16:24 UTC, merged