fix: add error message when SMILES not parsed
NFDI4Chem/nmrxiv pull request #753
Opened 2023-01-20 13:47 UTC by NRayya

Fixes #734

2023-01-21 19:04 UTC, NRayya commented
<img width="600" alt="image" src="https://user-images.githubusercontent.com/82588017/213882991-3af3db17-47d0-4047-9401-bcd8ffd0f150.png">

2023-01-27 10:41 UTC, CS76 requested changes

2023-01-27 10:41 UTC, CS76 commented on resources/js/Pages/Study/About.vue
> +            }
Use OCL molecule module to read smiles and generate molecule. If there are any errors, then display the appropriate message.

2023-01-27 10:41 UTC, CS76 commented on resources/js/Pages/Study/About.vue
> +            }
let mol = OCL.molecule.fromSmiles("CCCC")

https://cheminfo.github.io/openchemlib-js/classes/Molecule.html#fromSmiles

2023-08-01 10:29 UTC, closed without merging