Add Announcement Controller / Actions / Frontend Pages to manage announcements-Commit1
NFDI4Chem/nmrxiv pull request #89
Opened 2022-01-14 10:55 UTC by NishaSharma14

Closes #70

2022-02-08 13:07 UTC, CS76 requested changes

2022-02-08 13:07 UTC, vcnainala commented on app/Http/Controllers/Admin/AnnouncementController.php
> +    }
Remove unused code functions added by the CLI bootstrapped functions.

2022-02-21 09:26 UTC, NishaSharma14 commented on app/Http/Controllers/Admin/AnnouncementController.php
> +    }
I left this as a placeholder for any future amendments.

2022-02-21 09:36 UTC, NishaSharma14 commented on app/Http/Controllers/Admin/AnnouncementController.php
> +    }
Updated the PR with review changes.

2022-04-07 13:28 UTC, closed without merging